# -*- coding: utf-8 -*-
"""program.py
"""

print("Neden kaçtın neden?")
print("Mesut olurduk belki")
print("Korkuttum mu seni?")
print("Benden ne zarar gelir ki?")
print()
print("Seni seyretmem, gezmem lazımdı")
print("Bu yolun sonunu bulmam lazımdı")
print("Seni tanımam, bilmem lazımdı")
print("Bu hikâyeye bir son lazımdı")
print()
print("Öyle uzaktan uzaktan hiç konuşmadan nasıl da bağladın beni?")
print("Hani bi' geldin bi' kayboldun, esrarlı mağrurdun, aklıma sardım seni")
print("Öyle uzaktan uzaktan hiç konuşmadan nasıl da bağladın beni?")
print("Hani bi' geldin bi' kayboldun, esrarlı mağrurdun, aklıma sardım seni")
print()
print("Nedir sırrın ne senin?")
print("Çekip bıraktım, sen kimsin?")
print("Toz ol, derdim bitsin")
print("Aklım aşkını yensin")
print()
print("Seni seyretmem, gezmem lazımdı")
print("Bu yolun sonunu bulmam lazımdı")
print("Seni tanımam, bilmem lazımdı")
print("Dudaklarıma bir veda lazımdı")
print()
print("Öyle uzaktan uzaktan hiç konuşmadan nasıl da bağladın beni?")
print("Hani bi' geldin bi' kayboldun, esrarlı mağrurdun, aklıma sardım seni")
print("Öyle uzaktan uzaktan hiç konuşmadan nasıl da bağladın beni?")
print("Hani bi' geldin bi' kayboldun, esrarlı mağrurdun, aklıma sardım seni")
print()
print("Aklıma sardım seni, aklıma sardım seni")

