	disp("Neden kaçtın neden?");
	disp("Mesut olurduk belki");
	disp("Korkuttum mu seni?");
	disp("Benden ne zarar gelir ki?");
	disp();
	disp("Seni seyretmem, gezmem lazımdı");
	disp("Bu yolun sonunu bulmam lazımdı");
	disp("Seni tanımam, bilmem lazımdı");
	disp("Bu hikâyeye bir son lazımdı");
	disp();
	disp("Öyle uzaktan uzaktan hiç konuşmadan nasıl da bağladın beni?");
	disp("Hani bi' geldin bi' kayboldun, esrarlı mağrurdun, aklıma sardım seni");
	disp("Öyle uzaktan uzaktan hiç konuşmadan nasıl da bağladın beni?");
	disp("Hani bi' geldin bi' kayboldun, esrarlı mağrurdun, aklıma sardım seni");
	disp();
	disp("Nedir sırrın ne senin?");
	disp("Çekip bıraktım, sen kimsin?");
	disp("Toz ol, derdim bitsin");
	disp("Aklım aşkını yensin");
	disp();
	disp("Seni seyretmem, gezmem lazımdı");
	disp("Bu yolun sonunu bulmam lazımdı");
	disp("Seni tanımam, bilmem lazımdı");
	disp("Dudaklarıma bir veda lazımdı");
	disp();
	disp("Öyle uzaktan uzaktan hiç konuşmadan nasıl da bağladın beni?");
	disp("Hani bi' geldin bi' kayboldun, esrarlı mağrurdun, aklıma sardım seni");
	disp("Öyle uzaktan uzaktan hiç konuşmadan nasıl da bağladın beni?");
	disp("Hani bi' geldin bi' kayboldun, esrarlı mağrurdun, aklıma sardım seni");
	disp();
	disp("Aklıma sardım seni, aklıma sardım seni");
  